{{- if .Values.metrics.serviceMonitor.enabled }}
---
# Copyright (c) Walmart Inc.

# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-svc-mon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: admin-hs
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - targetPort: 19092 #metrics port on headless services
      path: /prometheus/v1/values
{{- end }}