{{ if .Values.configserver.virtualService.enabled }}
---
# Copyright (c) Walmart Inc.

# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: vespa-config
    version: v1
  name: vs-config-{{ .Values.clusterName }}-vespa
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - gateway-config-{{ .Values.clusterName }}-vespa-{{ .Values.deployEnv }}
  hosts:
    - config-{{ include "dnsHostname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: config
            port:
              number: {{ .Values.configserver.ports.port1 }}
{{ end }}