{{- if .Values.configserver.pdb.enabled -}}
  {{- if ( gt ( int .Values.configserver.replicas ) 1 ) -}}
---
# Copyright (c) Walmart Inc.

# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.deployEnv }}-config-pdb
spec:
  minAvailable: {{ include "pdbMinPods" ( list .Values.configserver.replicas .Values.configserver.pdb.thresholds.minPodsPercentage .Values.configserver.pdb.thresholds.minPodsCount ) }}
  selector:
    matchLabels: 
      app: config
  {{- end -}}
{{- end -}}