name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check if this is a release commit
        id: check-release
        run: |
          # Skip if this is already a changelog update commit
          if git log -1 --pretty=%B | grep -q "\[skip ci\]"; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping changelog update - this is an automated commit"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Changelog
        if: steps.check-release.outputs.skip == 'false'
        run: |
          # Make script executable and run it
          chmod +x scripts/generate-changelog.sh
          ./scripts/generate-changelog.sh
          
          # Check if changelog was updated
          if git diff --name-only | grep -q "CHANGELOG.md"; then
            echo "📝 Changelog updated automatically"
            git add CHANGELOG.md
            git commit -m "chore: update changelog [skip ci]"
            git push origin main
          else
            echo "ℹ️ No changelog updates needed"
          fi
