name: Update Changelog

on:
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create a PR with changelog updates'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Generate Changelog
        run: |
          # Make script executable and run it
          chmod +x scripts/generate-changelog.sh
          ./scripts/generate-changelog.sh

      - name: Check for changelog changes
        id: changes
        run: |
          if git diff --name-only | grep -q "CHANGELOG.md"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "📝 Changelog has been updated"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changelog updates needed"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true' && inputs.create_pr == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog"
          title: "chore: Update changelog"
          body: |
            This PR updates the changelog based on recent commits.
            
            **Auto-generated by**: Update Changelog workflow
          branch: update-changelog
          delete-branch: true

      - name: Show changelog diff
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "📋 Changelog changes:"
          git diff CHANGELOG.md
