name: Helm Chart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Install helm unittest plugin
      run: helm plugin install https://github.com/helm-unittest/helm-unittest

    - name: Run helm lint
      run: make lint

    - name: Run helm tests
      run: make test

    - name: Run helm template render
      run: make render
