name: PR Changelog Update

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog
        run: |
          # Make script executable and run it
          chmod +x scripts/generate-changelog.sh
          ./scripts/generate-changelog.sh

      - name: Check for changelog changes
        id: changes
        run: |
          if git diff --name-only | grep -q "CHANGELOG.md"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "📝 Changelog needs to be updated"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Changelog is already up to date"
          fi

      - name: Commit changelog updates
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog for PR changes

          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push origin ${{ github.head_ref }}

      - name: Comment on PR
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Changelog Updated**\n\nThe changelog has been automatically updated based on the commits in this PR. Please review the changes in `CHANGELOG.md`.'
            })
