name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:  # This enables the "Run workflow" button

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz
          tar -xzf chart-releaser_1.6.1_linux_amd64.tar.gz
          sudo mv cr /usr/local/bin/cr

      - name: Check if gh-pages branch exists
        id: check-branch
        run: |
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create gh-pages branch if it doesn't exist
        if: steps.check-branch.outputs.exists == 'false'
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          # Create a simple index.html
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Vespa Helm Charts</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
              .code { background: #f4f4f4; padding: 10px; border-radius: 5px; font-family: monospace; }
            </style>
          </head>
          <body>
            <h1>🚀 Vespa Helm Charts Repository</h1>
            <p>Add this repository to Helm:</p>
            <div class="code">helm repo add vespa https://walmartlabs.github.io/vespa-helm</div>
            <p>Install Vespa:</p>
            <div class="code">helm install my-vespa vespa/vespa</div>
            <p><a href="https://github.com/walmartlabs/vespa-helm">📚 Documentation</a></p>
          </body>
          </html>
          EOF
          # Create initial index.yaml
          cat > index.yaml << 'EOF'
          apiVersion: v1
          entries: {}
          generated: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EOF
          git add index.html index.yaml
          git commit -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout main

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

