name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Check for chart changes
        id: changes
        run: |
          # Check if there are any charts to process
          if [ ! -d "charts" ] || [ -z "$(find charts -name "Chart.yaml" -type f)" ]; then
            echo "No charts found in charts/ directory"
            exit 1
          fi
          
          # List charts for debugging
          echo "Found charts:"
          find charts -name "Chart.yaml" -type f | xargs -I {} dirname {}

      - name: Ensure gh-pages branch exists and is accessible
        run: |
          # Check if gh-pages branch exists remotely
          if ! git ls-remote --exit-code --heads origin gh-pages >/dev/null 2>&1; then
            echo "Creating initial gh-pages branch..."
            # Create and push an initial gh-pages branch
            git checkout --orphan gh-pages
            git rm -rf .
            
            # Create minimal index.yaml
            cat > index.yaml << 'EOF'
          apiVersion: v1
          entries: {}
          generated: "2024-01-01T00:00:00Z"
          EOF
            
            # Create index.html
            cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head><title>Vespa Helm Charts</title></head>
          <body>
            <h1>Vespa Helm Charts Repository</h1>
            <p>Repository is being set up...</p>
          </body>
          </html>
          EOF
            
            git add index.yaml index.html
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
            
            echo "✅ gh-pages branch created successfully"
          else
            echo "✅ gh-pages branch already exists"
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true

